.TH xpac 8 "February 14, 2018" "version 1.0"
.SH NAME
xpac - A Cross-platform Package Manager

.SH SYNOPSIS

.SH DESCRIPTION

.SH COMMANDS
xpac install <package_name>
.br
xpac <package_name>
.br
xpac install --version <package_name>
.br
xpac install --compile <package_name>
.br
xpac update
xpac upgrade
xpac list
xpac remove <package_name>
xpac remove --cleanup


.SH HISTORY

.SH BUGS

.SH AUTHORS
Anunai Ishan,
Adit Kumar,
Amol Moses Jha,
Parth Shelgaonkar
